name: MagicSpellsFactions
version: $project.ext.magicspellsData.stringVersionFactions
main: com.nisovin.magicspells.factions.MagicSpellsFactions
depend: [ MagicSpells, Factions ]
authors: [nisovin, TheComputerGeek2]
