name: MagicSpellsShop
version: $project.ext.magicspellsData.stringVersionShop
main: com.nisovin.magicspells.shop.MagicSpellsShop
author: nisovin
depend: [MagicSpells]
softdepend: [Vault]
permissions:
    magicspells.createsignshop:
        description: Create a spell shop
        default: op
